Upgrade Ruby version to 3.18
andrewmcodes/standardrb-action pull request #20
Opened 2023-06-05 08:58 UTC by BWherryImpero

We're getting errors using this action as the installed version of Ruby is 2.6 and current versions of standard (via the Rubocop dependency) require a Ruby version of 2.7+.

This PR updates the version of Ruby to 3.2.2

2023-06-18 10:33 UTC, madhums commented
@andrewmcodes could you please have a look at this?

2023-06-18 10:43 UTC, madhums commented
Perhaps there should be a way to specify the ruby version from the workflow file so that it can take the right version.

2023-06-18 14:04 UTC, madhums reviewed
Perhaps there should be a way to specify the ruby version from the workflow file so that it can the version used in the project (from `.ruby-version` file instead of hardcoding like this)

2023-06-19 08:52 UTC, BWherryImpero commented
> Perhaps there should be a way to specify the ruby version from the workflow file so that it can the version used in the project (from `.ruby-version` file instead of hardcoding like this)

Good shout. In this instance, it would need to be a [build argument](https://docs.docker.com/engine/reference/commandline/build/#build-arg).

2023-06-20 10:37 UTC, madhums commented
And it does not seem to have support https://github.com/orgs/community/discussions/25241 There are some workarounds for it though.

2023-08-29 11:28 UTC, edwinv commented
This issue makes this Github action completely unusable now. The latest versions of StandardRB require a later Ruby version. I'm wondering if the Ruby version pinning is required. Why not always use the latest version to also be compatible with the latest versions of StandardRB? This prevents the need for build arguments.

2024-01-26 15:10 UTC, Samuelodan commented
I wanted to try out the action today, and I ran into this issue. Now, Bundler needs at least Ruby 3.0 to install.
Shouldn't this be an easy merge? I wonder what's up.

2024-02-13 23:32 UTC, jlurena approved these changes

2024-02-26 11:11 UTC, madhums requested changes
Can we use custom build argument as suggested here? https://github.com/orgs/community/discussions/25241#discussioncomment-3247045

That way we end up using the ruby-version of the project. Note that not everyone uses the same version of ruby.

2024-03-20 01:51 UTC, kmcphillips commented
@andrewmcodes would it be possible to merge this?

2024-03-20 02:04 UTC, kmcphillips commented
For anyone finding this, the workaround is to use @BWherryImpero 's branch:

```yaml
      - name: StandardRB Linter
        # uses: andrewmcodes/standardrb-action@v1.0.0 # This is mainline
        uses: BWherryImpero/standardrb-action@upgrade-ruby-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2024-04-09 21:40 UTC, merged

2024-04-09 21:50 UTC, Samuelodan commented
Hallelujah! It's been merged! I was gonna fork it and change the one line for the mean time. Didn't realize someone already did.

Thanks, Andrew ❤️

2024-04-09 22:33 UTC, andrewmcodes commented
@kmcphillips you should be able to use `v2.0.0` now.

@Samuelodan no problem! 

Please do consider just saving on your execution time by replacing this action with the following:

```yaml
  standardrb:
    name: StandardRB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec standardrb --format github --parallel
```

Which will create the annotations for you just like this action does but without the extra overhead.